---
driver:
  name: vagrant

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://docs.vagrantup.com/v2/networking/forwarded_ports.html

  network:
    - ["private_network", { type: 'dhcp' }]
   # - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # require_chef_omnibus: 12.5.0

platforms:
  - name: ubuntu-14.04
    run_list: recipe[apt]
  - name: ubuntu-15.04
    run_list: recipe[apt]
  - name: debian-8.1
    run_list: recipe[apt]
    attributes:
      netatalk:
        install_method: 'deb_build'
  - name: centos-7.1

suites:
  - name: default
    run_list: recipe[test::default]
    attributes:
  - name: two_volumes
    run_list: recipe[test::two_volumes]
    attributes:
  - name: full
    run_list:
      - recipe[setup]
      - recipe[jml-defaults]
      - recipe[time_machine::volumes]
    includes: centos-7.1
