name 'time_machine'
maintainer 'J. Morgan Lieberthal'
maintainer_email 'j.morgan.lieberthal@gmail.com'
license 'MIT'
description 'Installs/Configures time_machine'
long_description 'Installs/Configures time_machine'
version '0.1.7'

depends 'netatalk', '~> 0.1'
depends 'chef-vault', '~> 1.3'
depends 'chef-sugar', '~> 3.1'
